spring:
  application:
    name: pii-scanner-redactor
  threads:
    virtual:
      enabled: true
server:
  port : 8080


pii:
  enc:
    keyB64: sVATyjrcdmBs1zK0ir2vZt3rIT08aDo5m44yeJy2Vk0=
  token:
    prefix: PIIENC

thread:
  count: 33
  count-for-speedup: 32

variables:
  single-thread-time: 274725